name: Nightly Build for rolling

on:
  schedule:
    - cron: '0 13 * * *'  # Runs every day at midnight, 13:00 UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:rolling
      env:
        ROS_DISTRO: rolling
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Build with ROS rolling
        shell: bash
        run: |
          ./scripts/github_workflows.sh
